name: Standard Reusable Deploy

on:
  workflow_call:
    # KHAI BÁO CÁC SECRET ĐỂ NHẬN TỪ DỰ ÁN CON
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Vẫn giữ permissions ở đây
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set Lowercase Repo Name
        run: |
          echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/${{ env.REPO_NAME }}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f
